package com.globalco.domain;

public enum SkillCategory {
    PROGRAMMING_LANGUAGES,
    FRAMEWORKS,
    DATABASES,
    CLOUD_PLATFORMS,
    DEVOPS,
    MOBILE_DEVELOPMENT,
    FRONTEND_DEVELOPMENT,
    BACKEND_DEVELOPMENT,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    ARTIFICIAL_INTELLIGENCE,
    CYBER_SECURITY,
    NETWORKING,
    UI_UX_DESIGN,
    PROJECT_MANAGEMENT,
    BUSINESS_ANALYSIS,
    QUALITY_ASSURANCE,
    DESIGN,
    SOFT_SKILLS,
    TOOLS,
    LANGUAGE,
    OTHER
}
