server:
  port: 8888
spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/santanu1998/Ai-Powered-Job-Portal-Config"
          clone-on-start: true
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true